config:
  data:
    data_root: /project/scratch/p200981/spark2024
    train_csv: train.csv
    val_csv: val.csv
    image_root: images
    mask_root: mask
    num_classes: 3
    class_names:
    - background
    - spacecraft_body
    - solar_panels
  model:
    variant: b2
    pretrained: ade20k
    freeze_backbone: false
    decoder_embed_dim: 768
    dropout: 0.1
  training:
    epochs: 300
    patience: 30
    image_size: 512
    batch_size: 16
    gradient_accumulation_steps: 1
    num_workers: 8
    validate_every: 1
    precision: fp32
    optimizer:
      type: adamw
      lr: 6e-5
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: 1e-8
    scheduler:
      type: warmup_cosine
      warmup_epochs: 5
      warmup_lr: 1e-7
      min_lr: 1e-6
      power: 1.0
    loss:
      type: ce_dice
      ce_weight: 0.5
      dice_weight: 0.5
      class_weights: null
      label_smoothing: 0.0
      focal_gamma: 2.0
    gradient_clip: 1.0
    resume: /project/home/p200776/u103235/cvia/CVIA-25-project-team-theta/model_weights_segformer/segformer_final
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.5
    rotation_limit: 30
    scale_limit: 0.2
    shift_limit: 0.1
    brightness_limit: 0.2
    contrast_limit: 0.2
    saturation_limit: 0.2
    hue_limit: 0.1
    random_crop: false
    crop_size: 448
    coarse_dropout: false
    coarse_dropout_prob: 0.3
    normalize:
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  output:
    save_path: model_weights_segformer_b2resumed
    checkpoint_every: 10
    keep_only_best: false
    save_plots: true
    log_every: 20
  deepspeed:
    zero_stage: 1
    offload_optimizer: false
    offload_params: false
    overlap_comm: true
    reduce_bucket_size: 500000000
    allgather_bucket_size: 500000000
  experiment:
    name: null
    seed: 42
    deterministic: false
    debug_mode: false
    debug_samples: 100
  hardware:
    num_nodes: null
    gpus_per_node: null
    cudnn_benchmark: true
    allow_tf32: true
runtime:
  timestamp: '2026-01-07 08:00:58'
  world_size: 16
  cuda_version: '12.6'
  pytorch_version: !!python/object/new:torch.torch_version.TorchVersion
  - 2.9.1+cu126
  hostname: mel2130
  slurm_job_id: '3916206'
  slurm_num_nodes: '4'
